# Generated by Django 4.1 on 2022-09-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_join_us_password_join_us_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join_us',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
