# Generated by Django 4.1 on 2022-09-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_join_us_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join_us',
            name='email',
            field=models.CharField(max_length=12),
        ),
    ]
