# Generated by Django 4.1 on 2022-09-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_join_us_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('quary', models.CharField(max_length=60)),
                ('desc', models.CharField(max_length=250)),
                ('member', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='join_us',
            name='email',
            field=models.CharField(max_length=32),
        ),
    ]
