# Generated by Django 4.1 on 2022-10-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_contact_alter_join_us_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='python',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='join_us',
            name='resume',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
    ]
