# Generated by Django 4.1 on 2022-10-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_python_alter_join_us_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='python',
            name='description',
            field=models.TextField(),
        ),
    ]
