# Generated by Django 4.1 on 2022-10-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_alter_python_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='questionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=50)),
                ('Solution', models.TextField()),
            ],
        ),
    ]
