# Generated by Django 4.1 on 2022-10-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_questionanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='javaScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='Question',
            field=models.CharField(max_length=500),
        ),
    ]
